blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/otmane-el-aloi/imposter/discussions
    about: Please ask questions and share ideas in our GitHub Discussions.
